import PDFDocument from "pdfkit";

// ── Design tokens ─────────────────────────────────────────────────────────────
const C = {
    primary: "#4F46E5",
    dark: "#111827",
    muted: "#6B7280",
    green: "#16A34A",
    yellow: "#CA8A04",
    red: "#DC2626",
    orange: "#EA580C",
    bg: "#F9FAFB",
    border: "#E5E7EB",
};

const M = 48;                      // left / right margin
const CW = 595.28 - M * 2;         // usable content width ≈ 499 pts
const FOOTER_Y = 810;               // footer starts here (A4 height ≈ 841)

// Hard ceiling per section — guarantees the whole report fits on one page
const MAX_ITEMS = 5;
const MAX_KEYWORDS = 10;

// ── Score helpers ─────────────────────────────────────────────────────────────
const scoreColor = s => s >= 75 ? C.green : s >= 50 ? C.yellow : C.red;
const scoreLabel = s => s >= 75 ? "Strong" : s >= 50 ? "Moderate" : "Needs Work";

/**
 * Generates a single-page PDF for the given report and pipes it to `dest`.
 * Uses bufferPages so we can stamp the footer before flushing.
 */
export const generateReportPDF = (report, dest) => {
    const doc = new PDFDocument({
        size: "A4",
        margins: { top: M, bottom: M, left: M, right: M },
        bufferPages: true,
        autoFirstPage: true,
    });

    doc.pipe(dest);

    const isJD = report.analysis_type === "jd";

    // ── Header bar ────────────────────────────────────────────────────────────
    doc.rect(0, 0, 595.28, 64).fill(C.primary);
    doc.fillColor("#fff").fontSize(20).font("Helvetica-Bold").text("ResumeIQ", M, 18);
    doc.fontSize(9).font("Helvetica").text("AI-Powered Resume Analysis Report", M, 42);
    doc.y = 72;

    // ── Meta line ─────────────────────────────────────────────────────────────
    const typeLabel = isJD ? "JD Match Analysis" : `Role: ${report.role ?? "General"}`;
    const dateStr = new Date(report.created_at).toLocaleDateString("en-IN", {
        day: "numeric", month: "long", year: "numeric",
    });

    doc.fillColor(C.muted).fontSize(9).font("Helvetica")
        .text(`${typeLabel}   ·   ${dateStr}`, M, doc.y, { width: CW });
    doc.moveDown(0.4);
    doc.moveTo(M, doc.y).lineTo(M + CW, doc.y).strokeColor(C.border).lineWidth(0.5).stroke();
    doc.moveDown(0.6);

    // ── Score boxes ───────────────────────────────────────────────────────────
    const scoreY = doc.y;
    const bw = isJD ? (CW - 10) / 2 : CW;  // box width

    scoreBox(doc, M, scoreY, bw, "ATS SCORE", report.score);
    if (isJD && report.match_score != null) {
        scoreBox(doc, M + bw + 10, scoreY, bw, "JD MATCH SCORE", report.match_score);
    }

    doc.y = scoreY + 58;
    doc.moveDown(0.7);

    // ── Missing Keywords (JD only) ────────────────────────────────────────────
    const keywords = (Array.isArray(report.missing_keywords) ? report.missing_keywords : [])
        .filter(k => k && String(k).trim())
        .slice(0, MAX_KEYWORDS);

    if (isJD && keywords.length > 0) {
        sectionTitle(doc, "Missing Keywords", C.orange);
        doc.moveDown(0.3);

        let kx = M, ky = doc.y;
        doc.font("Helvetica").fontSize(8);
        keywords.forEach(kw => {
            const kwStr = String(kw);
            const tw = doc.widthOfString(kwStr) + 16;
            if (kx + tw > M + CW) { kx = M; ky += 18; }
            doc.roundedRect(kx, ky, tw, 16, 3).fillAndStroke("#FFF7ED", "#FDBA74");
            doc.fillColor(C.orange).font("Helvetica").fontSize(8)
                .text(kwStr, kx + 8, ky + 4, { width: tw - 16, lineBreak: false });
            kx += tw + 5;
        });

        doc.y = ky + 20;
        doc.moveDown(0.5);
    }

    // ── Content sections ──────────────────────────────────────────────────────
    itemSection(doc, "Strengths", report.strengths, "#F0FDF4", "#86EFAC", C.green);
    itemSection(doc, "Weaknesses", report.weaknesses, "#FEFCE8", "#FDE68A", C.yellow);
    itemSection(doc, "Suggestions", report.suggestions, "#EFF6FF", "#BFDBFE", "#1D4ED8");

    // ── Footer on page 1 (and any overflow pages) ─────────────────────────────
    const { count, start } = doc.bufferedPageRange();
    for (let i = 0; i < count; i++) {
        doc.switchToPage(start + i);
        doc.rect(0, FOOTER_Y, 595.28, 841.89 - FOOTER_Y).fill("#F9FAFB");
        doc.fillColor(C.muted).fontSize(7).font("Helvetica")
            .text("Generated by ResumeIQ · resumeiq.app", M, FOOTER_Y + 12, {
                width: CW, align: "center",
            });
    }

    doc.flushPages();
    doc.end();
};

// ── Score box ─────────────────────────────────────────────────────────────────
function scoreBox(doc, x, y, w, label, rawScore) {
    const score = typeof rawScore === "number" ? rawScore : 0;
    doc.roundedRect(x, y, w, 56, 5).fillAndStroke(C.bg, C.border);
    doc.fillColor(C.muted).fontSize(7).font("Helvetica-Bold").text(label, x + 10, y + 8, { width: w - 20 });
    doc.fillColor(scoreColor(score)).fontSize(30).font("Helvetica-Bold").text(String(score), x + 10, y + 18, { width: 60 });
    doc.fillColor(C.muted).fontSize(9).font("Helvetica").text(`/ 100  —  ${scoreLabel(score)}`, x + 55, y + 28);
}

// ── Section title ─────────────────────────────────────────────────────────────
function sectionTitle(doc, text, color) {
    doc.fillColor(color).fontSize(12).font("Helvetica-Bold").text(text, M, doc.y, { width: CW });
}

// ── Bullet section ────────────────────────────────────────────────────────────
function itemSection(doc, title, items, bgColor, borderColor, textColor) {
    const list = (Array.isArray(items) ? items : [])
        .filter(it => it && String(it).trim())
        .slice(0, MAX_ITEMS);

    if (list.length === 0) return;

    sectionTitle(doc, title, textColor);
    doc.moveDown(0.3);

    list.forEach((item, i) => {
        const txt = String(item);
        const txtH = doc.fontSize(9).heightOfString(txt, { width: CW - 28 });
        const bH = Math.max(txtH + 10, 22);
        const y = doc.y;

        doc.roundedRect(M, y, CW, bH, 4).fillAndStroke(bgColor, borderColor);
        doc.fillColor(textColor).fontSize(9).font("Helvetica-Bold")
            .text("•", M + 10, y + (bH - 9) / 2, { lineBreak: false });
        doc.fillColor(C.dark).fontSize(9).font("Helvetica")
            .text(txt, M + 22, y + (bH - txtH) / 2, { width: CW - 28, lineBreak: true });

        doc.y = y + bH + (i < list.length - 1 ? 3 : 0);
    });

    doc.moveDown(0.5);
}
