import PDFDocument from "pdfkit";

// ── Palette ──────────────────────────────────────────────────────────────────
const COLORS = {
    primary: "#4F46E5",
    dark: "#111827",
    muted: "#6B7280",
    green: "#16A34A",
    yellow: "#CA8A04",
    red: "#DC2626",
    orange: "#EA580C",
    sectionBg: "#F9FAFB",
    border: "#E5E7EB",
};

const M = 50;        // page margin
const CONTENT_W = 495; // A4 width (595) - 2 * M

// ── Helpers ───────────────────────────────────────────────────────────────────
function scoreColor(s) {
    if (s >= 75) return COLORS.green;
    if (s >= 50) return COLORS.yellow;
    return COLORS.red;
}
function scoreLabel(s) {
    if (s >= 75) return "Strong";
    if (s >= 50) return "Moderate";
    return "Needs Work";
}

/**
 * Generate a formatted PDF for the given report and stream it to `dest`.
 * @param {object} report - Full report row from DB
 * @param {object} dest   - Node Writable (Express res)
 */
export const generateReportPDF = (report, dest) => {
    // bufferPages = true: hold all pages in memory so we can stamp footers
    // on ALL pages at once before flushing.
    const doc = new PDFDocument({
        size: "A4",
        margins: { top: M, bottom: 80, left: M, right: M },
        bufferPages: true,
        autoFirstPage: true,
    });

    doc.pipe(dest);

    const isJD = report.analysis_type === "jd";

    // ── Page 1: Header bar ───────────────────────────────────────────────────
    doc.rect(0, 0, doc.page.width, 70).fill(COLORS.primary);
    doc.fillColor("#fff").fontSize(22).font("Helvetica-Bold").text("ResumeIQ", M, 22);
    doc.fontSize(10).font("Helvetica").text("AI-Powered Resume Analysis Report", M, 48);
    doc.y = 80;

    // ── Meta row ─────────────────────────────────────────────────────────────
    const label = isJD ? "JD Match Analysis" : `Role: ${report.role ?? "General"}`;
    const date = new Date(report.created_at).toLocaleDateString("en-IN", {
        day: "numeric", month: "long", year: "numeric",
    });
    doc.fillColor(COLORS.muted).fontSize(10).font("Helvetica")
        .text(`${label}   ·   Generated on ${date}`, M, doc.y, { width: CONTENT_W });
    doc.moveDown(0.6);
    doc.moveTo(M, doc.y).lineTo(M + CONTENT_W, doc.y).strokeColor(COLORS.border).lineWidth(1).stroke();
    doc.moveDown(0.8);

    // ── Score boxes ───────────────────────────────────────────────────────────
    const scoreY = doc.y;
    const boxW = isJD ? (CONTENT_W - 12) / 2 : CONTENT_W;

    drawScoreBox(doc, M, scoreY, boxW, "ATS SCORE", report.score);
    if (isJD && report.match_score != null) {
        drawScoreBox(doc, M + boxW + 12, scoreY, boxW, "JD MATCH SCORE", report.match_score);
    }

    doc.y = scoreY + 82;
    doc.moveDown(1);

    // ── Missing Keywords (JD only) ────────────────────────────────────────────
    const keywords = Array.isArray(report.missing_keywords)
        ? report.missing_keywords.filter(k => k && String(k).trim())
        : [];

    if (isJD && keywords.length > 0) {
        ensureSpace(doc, 60);
        doc.fillColor(COLORS.orange).fontSize(13).font("Helvetica-Bold")
            .text("Missing Keywords", M, doc.y, { width: CONTENT_W });
        doc.moveDown(0.4);

        let kx = M, ky = doc.y;
        const chipH = 20, pad = 10, gap = 6;

        // Set font first so widthOfString uses the right metrics
        doc.font("Helvetica").fontSize(9);
        keywords.forEach(kw => {
            const kwStr = String(kw);
            const tw = doc.widthOfString(kwStr) + pad * 2;
            if (kx + tw > M + CONTENT_W) { kx = M; ky += chipH + gap; }
            doc.roundedRect(kx, ky, tw, chipH, 3).fillAndStroke("#FFF7ED", "#FDBA74");
            doc.fillColor(COLORS.orange).font("Helvetica").fontSize(9)
                .text(kwStr, kx + pad, ky + 5, { width: tw - pad * 2, lineBreak: false });
            kx += tw + gap;
        });

        doc.y = ky + chipH + 14;
        doc.moveDown(0.6);
    }

    // ── Bullet sections ───────────────────────────────────────────────────────
    drawBulletSection(doc, "Strengths", report.strengths, "#F0FDF4", "#86EFAC", COLORS.green);
    drawBulletSection(doc, "Weaknesses", report.weaknesses, "#FEFCE8", "#FDE68A", COLORS.yellow);
    drawBulletSection(doc, "Suggestions", report.suggestions, "#EFF6FF", "#BFDBFE", "#1D4ED8");

    // ── Stamp footer on every page ────────────────────────────────────────────
    const range = doc.bufferedPageRange();
    for (let i = 0; i < range.count; i++) {
        doc.switchToPage(range.start + i);
        const ph = doc.page.height, pw = doc.page.width;
        doc.rect(0, ph - 36, pw, 36).fill("#F9FAFB");
        doc.fillColor(COLORS.muted).fontSize(8).font("Helvetica")
            .text("Generated by ResumeIQ · resumeiq.app", M, ph - 22, {
                width: pw - M * 2, align: "center",
            });
    }

    doc.flushPages();
    doc.end();
};

// ── Score box helper ──────────────────────────────────────────────────────────
function drawScoreBox(doc, x, y, w, label, score) {
    const safeScore = typeof score === "number" ? score : 0;
    doc.roundedRect(x, y, w, 72, 6).fillAndStroke(COLORS.sectionBg, COLORS.border);
    doc.fillColor(COLORS.muted).fontSize(8).font("Helvetica-Bold")
        .text(label, x + 12, y + 10, { width: w - 20 });
    doc.fillColor(scoreColor(safeScore)).fontSize(36).font("Helvetica-Bold")
        .text(String(safeScore), x + 12, y + 22, { width: 80 });
    doc.fillColor(COLORS.muted).fontSize(10).font("Helvetica")
        .text(`/ 100  —  ${scoreLabel(safeScore)}`, x + 65, y + 36);
}

// ── Section rendering helper ──────────────────────────────────────────────────
function drawBulletSection(doc, title, items, bgColor, borderColor, textColor) {
    const validItems = Array.isArray(items)
        ? items.filter(item => item && String(item).trim().length > 0)
        : [];
    if (validItems.length === 0) return;

    ensureSpace(doc, 60);
    doc.fillColor(textColor).fontSize(13).font("Helvetica-Bold")
        .text(title, M, doc.y, { width: CONTENT_W });
    doc.moveDown(0.4);

    validItems.forEach((item, i) => {
        const itemStr = String(item);
        const textH = doc.heightOfString(itemStr, { width: CONTENT_W - 34 }) || 14;
        const boxH = textH + 16;

        ensureSpace(doc, boxH + 8);
        const y = doc.y;

        doc.roundedRect(M, y, CONTENT_W, boxH, 5).fillAndStroke(bgColor, borderColor);
        doc.fillColor(textColor).fontSize(10).font("Helvetica-Bold")
            .text("•", M + 12, y + 8, { lineBreak: false });
        doc.fillColor(COLORS.dark).fontSize(10).font("Helvetica")
            .text(itemStr, M + 26, y + 8, { width: CONTENT_W - 34, lineBreak: true });

        doc.y = y + boxH + (i < validItems.length - 1 ? 4 : 0);
    });

    doc.moveDown(0.8);
}

// ── Ensure minimum vertical space, add page if needed ─────────────────────────
function ensureSpace(doc, needed) {
    const available = doc.page.height - doc.page.margins.bottom - doc.y;
    if (available < needed) {
        doc.addPage();
    }
}
